### ISSUE TITLE
Empty blocks are lost when performing an undo operation

### ISSUE THREAD

**Issue by juanhurtado10** [kommitters/editorjs-undo#53]
## Context
https://user-images.githubusercontent.com/20125027/129673632-f1ec0d96-123f-46b2-b1b7-fc32fbe5089c.mov

**Comment by komaldembla** [comment]
Please find the list

Device, Browser, OS:  
 - Macbook Pro, Chrome (92.0.4515.107), MacOS Catalina
 
Editor.js version:  `2.22.0`

Plugins used with their versions: 
 - `editorjs/checklist` (1.3.0), 
 - `editorjs/delimiter` (1.2.0), 
 - `editorjs/header` (2.6.1)
 - `editorjs/link` (2.3.1)
 - `editorjs/list` (1.6.2)
 - `editorjs/paragraph` (2.8.0)
 - `editorjs/underline` (1.0.0)
 - `editorjs-text-color-plugin` (1.1.22)

**Comment by MrJuanGaviriaK** [comment]
Hi @komaldembla, @juanhurtado10 

I was reviewing this issue and I found the main reason for this behavior. Editor.js doesn't save empty blocks  between the data because an empty block is invalid data, so editorjs-undo can't manage it:

![Screen Shot 2021-08-19 at 11 08 56 AM](https://user-images.githubusercontent.com/45491405/130103779-8c5fc1c4-cb2f-4bdd-a9d6-7f2f32486beb.png)

On the other hand, editor.js allows injecting lines break with ENTER+SHIFT and you would get:
  
![Screen Shot 2021-08-19 at 11 15 01 AM](https://user-images.githubusercontent.com/45491405/130104723-798e8dec-ce05-4fc3-a643-599745c6afd2.png)

If you need a breake-line component, I would recommend you  [editorjs-break-line](https://github.com/kommitters/editorjs-break-line), editorjs-undo  works perfectly with this plugin

Best,
Juan Gaviria

**Comment by komaldembla** [comment]
Thanks for the quick response here @MrJuanGaviriaK!  I'll check the workarounds.

**Comment by juanhurtado10** [comment]
@komaldembla @MrJuanGaviriaK 

https://user-images.githubusercontent.com/1649973/132592356-07366fb1-227a-42b5-ad22-ae9e48517610.mov

After researching, I found that the following config allows the Undo plugin to recover the empty blocks.

```javascript
  paragraph: {
    class: Paragraph,
    inlineToolbar: true,
    config: {
      preserveBlank: true,
    },
  },
  ...
```

**Comment by komaldembla** [comment]
@juanhurtado10 - Thank you so much! This works :)
