### ISSUE TITLE
Not working with editorjs-table, empty rows are deleted

### ISSUE THREAD

**Issue by Frank-Mayer** [kommitters/editorjs-undo#76]
### Description

Undo deletes empty rows on a Table

### Environment

* Editor.js version: [@editorjs/editorjs](https://www.npmjs.org/package/@editorjs/editorjs)(^2.22.2)
* Plugins you use with their versions: [editorjs-undo](https://www.npmjs.org/package/editorjs-undo)(^1.0.1) [editorjs-table](https://www.npmjs.org/package/editorjs-table)(^1.4.10)
* Device, Browser, OS: MacBook Pro 2019, Chrome, macOS 12.1

### Current behavior

Adding table, enter some content
<img width="666" alt="Bildschirmfoto 2022-01-20 um 08 48 00" src="https://user-images.githubusercontent.com/53651857/150295453-4116fb71-f44a-451c-921b-a0356cec5d49.png">

Then Ctrl + Z
<img width="666" alt="Bildschirmfoto 2022-01-20 um 08 48 59" src="https://user-images.githubusercontent.com/53651857/150295566-ccb7d181-821e-4783-956c-242d72737a0e.png">

### Expected behavior

Only remove the text that was entered

### Additional context

My Application is currently available here:
- [live app](https://docdown.app)
- [source](https://github.com/Frank-Mayer/docdown)

**Comment by MarioRodriguezS** [comment]
@Frank-Mayer Hi there!
Thanks a lot for report the issue, however this issue is not related with editorjs-undo, it is related with editorjs-table. Basically, editorjs-table does not save empty rows, for example if you have: 
![imagen](https://user-images.githubusercontent.com/64106728/150617687-970e8a49-bf9b-45f6-ab32-38fe40e3a422.png)

the saved table will be stored as follows: 

![imagen](https://user-images.githubusercontent.com/64106728/150617731-89bc0ad1-3a08-40e8-b920-07074dca1b99.png)

And editorjs-undo works with the saved data way, I recommend you to report this issue in editorjs-table, asking to save empty rows, in this way it will woks as expected. 

Best,
Mario
